apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-app
    app.kubernetes.io/part-of: test-application
  name: node-app
  namespace: christianvogt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: node-app
    spec:
      containers:
      - image: quay.io/karthik_jk/node-app@sha256:364c9abbfa485b23675355ff3b5e6c99cd127cc312a94307746c564d2fe39015
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
